config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  # Rails information, in development mode, is provided at:
  #   localhost:3000/rails/info/properties
  #   localhost:3000/rails/info/routes

  # Email previews, in development mode, are provided at:
  #   localhost:3000/rails/mailers
  #
  # This is setup in specs/mailers/previews

  # AUTHENTICATION ROUTES (cookie-based via Clearance Gem)
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]
  resources :users, controller: "users", only: [:create] do
    resource :password, controller: "passwords", only: [:create, :edit, :update]
  end

  resources :users, only: [:update, :destroy]
  # Setup custom "edit_user" path specifically without "edit" in the URL which
  # is usually needed to differentiate between show and edit pages, in this
  # case there will be no show user page so "edit" path value is not needed.
  get "/users/:id" => "users#edit", :as => "edit_user"

  # The Clearance authentication gem by default does not provide email
  # confirmation. This thoughtbot article details how to add email confirmation
  # to Clearance:
  #   https://robots.thoughtbot.com/email-confirmation-with-clearance
  #
  # Setup a custom "confirm_email" path to validate that a newly signed-up user
  # actually is the owner of the specified email address. A confirmation link
  # (sent from UsersController#create via UserMailer#email_confirmation) will
  # be the following route which will contain both user's name and unique
  # confirmation token.
  get "/confirm_email/:name/:token" => "email_confirmations#update", :as => "confirm_email"

  get "log_in" => "clearance/sessions#new"
  get "log_in" => "clearance/sessions#new", :as => "sign_in"
  delete "log_out" => "clearance/sessions#destroy"
  get "sign_up" => "clearance/users#new"

  # API AUTHENTICATION ROUTES (JWT-based via custom application code)
  namespace :api, defaults: {format: :json} do
    post "log_in" => "sessions#create"
    post "passwords" => "passwords#create"
    put "users/passwords/:user_id/password" => "passwords#update"
    patch "users/passwords/:user_id/password" => "passwords#update"
    put "users/:id" => "users#update"
    patch "users/:id" => "users#update"
    delete "users/:id" => "users#destroy"
    post "users" => "users#create"
    get "confirm_email/:name/:token" => "email_confirmations#update"
    get "tokens/new" => "tokens#new"
  end

  # MISCELLANEOUS ROUTES
  root "misc_pages#home"
  get "home" => "misc_pages#home"
  get "about" => "misc_pages#about"
  get "details" => "misc_pages#details"

  # SIDEKIQ MANAGEMENT INTERFACE
  constraints(Clearance::Constraints::SignedIn.new { |user| user.admin? }) do
    mount Sidekiq::Web, at: "/sidekiq"
  end

  # ARTIST AND ALBUM ROUTES
  #
  # Nested resources, Artist and Album, both using FriendlyId with blank
  # controller names.
  #
  # Important, read the following, especially the "small problem" section:
  #   http://jasoncodes.com/posts/rails-3-nested-resource-slugs

  resources :genres, only: [:index, :create]

  resources :artists, only: [:index, :new, :create]
  get "/artists/:id/albums" => "artists/albums#index", :as => "albums_artist"

  get "/comments/:user_id" => "users/comments#index", :as => "user_comments"
  get "/comments/:user_id/comments" => "users/comments#comments"

  resources :albums, only: :index

  resources :artists, path: "", except: [:index, :new, :create] do
    resources :comments, module: :artists, only: [:index, :create, :destroy]
  end

  resources :artists, path: "", only: [] do
    resources :albums, path: "", except: :index do
      resources :comments, module: :albums, only: [:index, :create, :destroy]
    end
  end
end

app/models/artist.rb
# frozen_string_literal: true

class Artist < ApplicationRecord
  # ASSOCIATIONS
  has_many :albums, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  # FRIENDLY URL
  extend FriendlyId
  friendly_id :name, use: :slugged

  # VALIDATIONS
  validates :name, presence: true, uniqueness: {case_sensitive: false}

  VALID_WEBSITE_RE = %r{\Ahttps?://[\w\d\-.]*\z}.freeze
  validates :website, format: {with: VALID_WEBSITE_RE}, allow_blank: true

  # SCOPES
  scope :starts_with_letter, ->(letter) do
    where("substr(name, 1, 1) = ?", letter).order(:name)
  end

  # This complicated find-by-SQL scope is ranking results from the first part
  # of the union (artist name matches) higher than results from the second part
  # (artist description matches) by ordering first on rank and then by name.
  # Note, the virtual "rank" column added to each of the SELECT clauses means
  # UNION based deduplication will not work, hence a Ruby side "uniq" call is
  # used to deduplicate; for very large result sets this would be a problem,
  # however in this case it will be fine since there will be a limit of 250
  # records.
  scope :search, ->(query) do
    find_by_sql([<<-SQL.squish, query, query])
                   SELECT artists.*, 1 as rank
                     FROM artists
                     WHERE name @@ ?
                   UNION ALL
                   SELECT DISTINCT artists.*, 2 as rank
                     FROM artists
                     WHERE description @@ ?
                   ORDER BY rank, name ASC LIMIT 250
    SQL
      .uniq
  end

  # MODEL FILTER METHODS
  def self.list(params)
    if params.key?(:letter)
      Artist.starts_with_letter(params[:letter]).page(params[:page])
    elsif params.key?(:search)
      Kaminari.paginate_array(Artist.search(params[:search])).page(params[:page])
    else
      Artist.order(:name).page(params[:page])
    end
  end

  # VIEW HELPERS.
  #
  # Return a link with the "http(s)://(www.)" prefix stripped away.
  def website_link
    return unless website?

    @website_link ||= website.split("//")[1].sub(/^www\./, "")
  end
end

app/controllers/artists/albums_controller.rb
# frozen_string_literal: true

class Artists::AlbumsController < ApplicationController
  before_action :set_artist, only: [:index]

  def index
    @albums = Album.artist_albums(@artist.id, params)
    @order_name = if params[:newest]
      "newest"
    elsif params[:oldest]
      "oldest"
    elsif params[:longest]
      "longest"
    elsif params[:name]
      "name"
    end
    respond_to do |format|
      format.js
      format.json
    end
  end

  private

  def set_artist
    @artist = Artist.friendly.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The artist '#{params[:id]}' does not exist"
    redirect_to artists_path
  end
end

app/controllers/artists/comments_controller.rb
# frozen_string_literal: true

class Artists::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
    @commentable = Artist.friendly.find(params[:artist_id])
    @commentable_path = artist_path(@commentable)
  end
end

app/controllers/artists_controller.rb
# frozen_string_literal: true

class ArtistsController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = Artist.list(params)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def show
    @albums = Album.artist_albums(@artist.id)
    @comments = @artist.comments.list.page
    @comments_path = request.path + "/comments"
    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    @artist = Artist.new
    @back_link = request.referer || artists_path
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      flash[:notice] = "#{@artist.name} has been created"
      redirect_to @artist
    else
      flash.now[:alert] = "Artist could not be created"
      @back_link = artists_path
      render "new", status: :unprocessable_entity
    end
  end

  def edit
    @back_link = artist_path(@artist)
  end

  def update
    @artist.slug = nil
    if @artist.update(artist_params)
      flash[:notice] = "#{@artist.name} has been updated"
      redirect_to @artist
    else
      flash.now[:alert] = "Artist could not be updated"
      @back_link = artists_path
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    @artist.destroy!
    flash[:notice] = "#{@artist.name} has been removed"
    redirect_to artists_path
  end

  private

  def set_artist
    @artist = Artist.friendly.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    if request.format.html?
      flash[:alert] = "The artist '#{params[:id]}' does not exist"
      redirect_to artists_path
    else # JSON end-point
      head :not_found
    end
  end

  def artist_params
    params.require(:artist).permit(:name, :description, :wikipedia, :website)
  end
end

app/helpers/artists_helper.rb
# frozen_string_literal: true

module ArtistsHelper
  def commentable_path(comment)
    if comment.commentable_type == "Album"
      artist_album_path(
        comment.commentable.artist, comment.commentable, anchor: "comments"
      )
    elsif comment.commentable_type == "Artist"
      artist_path(comment.commentable, anchor: "comments")
    end
  end

  def commentable_path_for_api(comment)
    if comment.commentable_type == "Album"
      "artist/#{comment.commentable.artist.slug}/album/#{comment.commentable.slug}"
    elsif comment.commentable_type == "Artist"
      "artist/#{comment.commentable.slug}"
    end
  end

  def commentable_name(comment)
    name = ""

    if comment.commentable_type == "Album"
      name += comment.commentable.title
    elsif comment.commentable_type == "Artist"
      name += comment.commentable.name
    end

    name
  end
end

app/views/artists/_album.html.erb
<% cache [signed_in_as_admin?, artist, album] do %>
  <div class="album" data-behavior="artist-album-<%= album.id %>">
    <%= link_to [artist, album] do %>
      <%= image_tag(album.cover.small.url, class: "img-responsive") if album.cover? %>
    <% end %>
    <div class="title">
      <h2><%= link_to album.title, [artist, album] %></h2>
      <%= '<span class="icon">'.html_safe unless Rails.env.test? %>
        <% if signed_in_as_admin? %>
          <%= link_to edit_artist_album_path(album.artist, album) do %>
            <%= fa_icon "edit", text: "Edit" %>
          <% end %>
          <%= link_to artist_album_path(album.artist, album), remote: true, class: "spacer-left-xs", method: :delete, data: {confirm: "Are you sure you want to remove #{album.title}?"} do %>
            <%= fa_icon "remove", text: "Remove" %>
          <% end %>
        <% end %>
        <%= link_to albums_path(year: album.release_date.year), class: "spacer-left-xs" do %>
          <%= fa_icon "calendar", text: "#{album.release_date.year}" %>
        <% end %>
        <%= link_to albums_path(genre: album.genre.name), class: "spacer-left-xs" do %>
          <%= fa_icon "tag", text: "#{album.genre.name}" %>
        <% end %>
        <%= link_to artist_album_path(album.artist, album, anchor: "comments"), class: "artist-album-comments" do %>
          <%= fa_icon "comment-o", text: "#{album.comments_count}", class: "spacer-left-xs" %>
        <% end %>
      <%= '</span>'.html_safe unless Rails.env.test? %>
    </div>
    <h3 class="album-details"><small><%= "(#{album.tracks_count} Tracks, Time #{album.total_duration})" %></small></h3>
    <ul>
      <% album.tracks_summary.each do |track_title| %>
        <li><%= track_title %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/artists/_artist.html.erb
<% cache artist do %>
  <%= link_to artist do %>
    <div class="artist">
      <h2><%= artist.name %></h2>
      <% if artist.description? %>
        <p><%= artist.description %></p>
      <% end %>
      <span class="icon">
        <%= fa_icon "music", text: "#{artist.albums_count}" %>
        <%= fa_icon "comment-o", text: "#{artist.comments_count}", class: "spacer-left-xs" %>
      </span>
    </div>
  <% end %>
<% end %>

app/views/artists/_form.html.erb
<div class="well">
  <%= form_with model: artist, class: "form-horizontal", local: true, data: { turbo: false } do |f| %>
    <ul class="list-group" data-behavior="artist-form-errors">
      <% if artist.errors.any? %>
        <% artist.errors.full_messages.each do |msg| %>
          <li class="list-group-item list-group-item-danger"><%= msg %></li>
        <% end %>
      <% end %>
    </ul>

    <div class="form-group <%= error?(artist, :name) %>" data-behavior="artist-name">
      <%= f.label :name, class: "col-md-2 control-label" %>
      <div class="col-md-9">
        <%= f.text_field :name, class: "form-control", placeholder: "The Artist" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :wikipedia, class: "col-md-2 control-label" %>
      <div class="col-md-9">
        <%= f.text_field :wikipedia, class: "form-control", placeholder: "The_Artist" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :website, class: "col-md-2 control-label" %>
      <div class="col-md-9">
        <%= f.text_field :website, class: "form-control", placeholder: "http://www.theartist.com" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :description, class: "col-md-2 control-label" %>
      <div class="col-md-9">
        <%= f.text_area :description, rows: 7, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-2 col-md-9">
        <%= link_to "Cancel", back_link, class: "btn btn-default btn-sm" %>
        <%= f.button "Submit", class: "btn btn-success btn-sm", data: {disable_with: "#{fa_icon('spinner spin')} Submitting..."} %>
      </div>
    </div>
  <% end %>
</div>

app/views/artists/_sidebar.html.erb
<% cache "artists_sidebar", expires_in: 5.minutes do %>
  <aside id="artists-sidebar" class="col-lg-2">
    <section class="card">
      <div class="card-header">
        <h4 class="card-title">New Albums</h4>
      </div>
      <div class="new-albums list-group list-group-flush">
        <% Album.with_relations.most_recent.each do |album| %>
          <div class="album list-group-item">
            <h5><%= link_to album.title, [album.artist, album] %></h5>
            <h5>by <%= link_to album.artist.name, album.artist %></h5>
            <%= link_to [album.artist, album] do %>
              <%= image_tag(album.cover.small.url, class: "img-fluid mx-auto d-block") if album.cover? %>
            <% end %>
          </div>
        <% end %>
      </div>
    </section>

    <section class="card">
      <div class="card-header">
        <h4 class="card-title">New Comments</h4>
      </div>
      <div class="new-comments list-group list-group-flush">
        <% Comment.most_recent.each do |comment| %>
          <div class="comment list-group-item">
            <h5>
              <%= local_time_ago comment.created_at %> by
            </h5>
            <h5><%= link_to comment.user.name, user_comments_path(comment.user.slug) %></h5>
            <%= link_to user_comments_path(comment.user.slug) do %>
              <%= image_tag(gravatar_url(comment.user), class: "img-fluid mx-auto d-block") %>
            <% end %>
            <h5>
              in <%= link_to commentable_name(comment), commentable_path(comment) %>
            </h5>
          </div>
        <% end %>
      </div>
    </section>
  </aside>
<% end %>

app/views/artists/albums.js.erb
$("[data-behavior^=order-]").find("a").removeClass("active")
$("[data-behavior~=order-<%= @order_name %>]").find("a").addClass("active")
$("[data-behavior~=artist-albums]").empty();
$("[data-behavior~=artist-albums]").html("<%= j render partial: "album", collection: @albums, locals: {artist: @artist} %>");

app/views/artists/edit.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="page-header">
      <h1>Edit Artist</h1>
    </div>

    <%= render "form", artist: @artist, back_link: @back_link %>
  </div>
</div>

app/views/artists/index.html.erb
<% title("Platters - Artists") %>
<div class="row">
  <div class="col-md-10">
    <div id="artists">
      <div class="page-header">
        <div class="pull-left">
          <%= header_text_with_counter(:h1, "Artist", @artists.total_count) %>
        </div>
        <% if signed_in_as_admin? %>
          <div class="pull-right">
            <%= link_to new_artist_path, class: "action" do %>
              <%= fa_icon "plus" %> Artist
            <% end %>
          </div>
        <% end %>
        <div class="clearfix"></div>
      </div>

      <div class="list-choice text-center">
        <ul class="pagination pagination-sm">
          <li><%= link_to "All", artists_path %></li>
          <% unless params.key?(:search) %>
            <% ("A".."Z").each do |letter| %>
              <li data-behavior="artist-letter-picker" class="<%= letter_activity(params, letter) %>"><%= link_to letter, artists_path(letter: letter) %></li>
            <% end %>
          <% end %>
          <li><a class="search-link" title="Search" data-toggle="tooltip" data-behavior="artist-search-link"><%= fa_icon "search" %></a></li>
        </ul>
      </div>

      <%= render partial: "shared/search", locals: {type: "artist", path: artists_path} %>

      <% if @artists.empty? %>
        <h4 class="text-center">No matching artists</h4>
      <% else %>
        <%= render partial: "artist", collection: @artists %>
        <%= paginate @artists %>
      <% end %>
    </div>
  </div>

  <%= render partial: "sidebar" %>
</div>

app/views/artists/new.html.erb
<div class="row">
  <div class="col-lg-10 offset-lg-1">
    <div class="page-header">
      <h1>Add Artist</h1>
    </div>

    <%= render "form", artist: @artist, back_link: @back_link %>
  </div>
</div>

app/views/artists/show.html.erb
<% title(@artist.name) %>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div id="artist">
      <div class="page-header">
        <div class="pull-left">
          <h1><%= @artist.name %></h1>
        </div>
        <% if signed_in_as_admin? %>
          <div class="pull-right">
            <ul class="list-inline">
              <li>
                <%= link_to artist_path, class: "spacer-left-xs action", method: :delete, data: {confirm: "Are you sure you want to remove #{@artist.name}?"} do %>
                  <%= fa_icon "remove" %> Remove
                <% end %>
              </li>
              <li>
                <%= link_to edit_artist_path, class: "action" do %>
                  <%= fa_icon "edit" %> Edit
                <% end %>
              </li>
            </ul>
          </div>
        <% end %>
        <div class="clearfix"></div>
      </div>

      <div class="description">
        <p><%= @artist.description %></p>
        <% if @artist.wikipedia.present? %>
          <%= link_to "Wikipedia", "https://www.wikipedia.org/wiki/#{@artist.wikipedia}", target: "_blank", rel: "noopener noreferrer" %>
        <% end %>
      </div>

      <% if @artist.website.present? %>
        <div class="website">
          <span class="icon"><%= fa_icon "globe" %></span>
          <%= sanitize link_to(@artist.website_link, @artist.website, target: "_blank"), attributes: %w(href target) %>
        </div>
      <% else %>
        <div class="spacer-bottom-sm"></div>
      <% end %>

      <div class="page-header">
        <div class="pull-left">
          <%= header_text_with_counter(:h2, "Album", @albums.size) %>
        </div>
        <% if signed_in_as_admin? %>
          <div class="pull-right">
            <%= link_to new_artist_album_path(@artist), class: "action" do %>
              <%= fa_icon "plus" %> Album
            <% end %>
          </div>
        <% end %>
        <div class="clearfix"></div>
      </div>

      <% if !@albums.empty? %>
        <ul class="albums-order">
          <li data-behavior="order-newest"> <%= link_to "Newest",  albums_artist_path(newest: true),  remote: true, class: "active" %></li>
          <li data-behavior="order-oldest"> <%= link_to "Oldest",  albums_artist_path(oldest: true),  remote: true %></li>
          <li data-behavior="order-longest"><%= link_to "Longest", albums_artist_path(longest: true), remote: true %></li>
          <li data-behavior="order-name">   <%= link_to "Name",    albums_artist_path(name: true),    remote: true %></li>
        </ul>
      <% end %>

      <div data-behavior="artist-albums">
        <%= render partial: "album", collection: @albums, locals: {artist: @artist} %>
      </div>

      <div class="spacer-bottom-lg"></div>
      <%= render partial: "shared/comments", locals: {comments: @comments, comments_path: @comments_path, commentable: @artist, commentable_path: [@artist]} %>
    </div>
  </div>
</div>