config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  # Rails information, in development mode, is provided at:
  #   localhost:3000/rails/info/properties
  #   localhost:3000/rails/info/routes

  # Email previews, in development mode, are provided at:
  #   localhost:3000/rails/mailers
  #
  # This is setup in specs/mailers/previews

  # AUTHENTICATION ROUTES (cookie-based via Clearance Gem)
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]
  resources :users, controller: "users", only: [:create] do
    resource :password, controller: "passwords", only: [:create, :edit, :update]
  end

  resources :users, only: [:update, :destroy]
  # Setup custom "edit_user" path specifically without "edit" in the URL which
  # is usually needed to differentiate between show and edit pages, in this
  # case there will be no show user page so "edit" path value is not needed.
  get "/users/:id" => "users#edit", :as => "edit_user"

  # The Clearance authentication gem by default does not provide email
  # confirmation. This thoughtbot article details how to add email confirmation
  # to Clearance:
  #   https://robots.thoughtbot.com/email-confirmation-with-clearance
  #
  # Setup a custom "confirm_email" path to validate that a newly signed-up user
  # actually is the owner of the specified email address. A confirmation link
  # (sent from UsersController#create via UserMailer#email_confirmation) will
  # be the following route which will contain both user's name and unique
  # confirmation token.
  get "/confirm_email/:name/:token" => "email_confirmations#update", :as => "confirm_email"

  get "log_in" => "clearance/sessions#new"
  get "log_in" => "clearance/sessions#new", :as => "sign_in"
  delete "log_out" => "clearance/sessions#destroy"
  get "sign_up" => "clearance/users#new"

  # API AUTHENTICATION ROUTES (JWT-based via custom application code)
  namespace :api, defaults: {format: :json} do
    post "log_in" => "sessions#create"
    post "passwords" => "passwords#create"
    put "users/passwords/:user_id/password" => "passwords#update"
    patch "users/passwords/:user_id/password" => "passwords#update"
    put "users/:id" => "users#update"
    patch "users/:id" => "users#update"
    delete "users/:id" => "users#destroy"
    post "users" => "users#create"
    get "confirm_email/:name/:token" => "email_confirmations#update"
    get "tokens/new" => "tokens#new"
  end

  # MISCELLANEOUS ROUTES
  root "misc_pages#home"
  get "home" => "misc_pages#home"
  get "about" => "misc_pages#about"
  get "details" => "misc_pages#details"

  # SIDEKIQ MANAGEMENT INTERFACE
  constraints(Clearance::Constraints::SignedIn.new { |user| user.admin? }) do
    mount Sidekiq::Web, at: "/sidekiq"
  end

  # ARTIST AND ALBUM ROUTES
  #
  # Nested resources, Artist and Album, both using FriendlyId with blank
  # controller names.
  #
  # Important, read the following, especially the "small problem" section:
  #   http://jasoncodes.com/posts/rails-3-nested-resource-slugs

  resources :genres, only: [:index, :create]

  resources :artists, only: [:index, :new, :create]
  get "/artists/:id/albums" => "artists/albums#index", :as => "albums_artist"

  get "/comments/:user_id" => "users/comments#index", :as => "user_comments"
  get "/comments/:user_id/comments" => "users/comments#comments"

  resources :albums, only: :index

  resources :artists, path: "", except: [:index, :new, :create] do
    resources :comments, module: :artists, only: [:index, :create, :destroy]
  end

  resources :artists, path: "", only: [] do
    resources :albums, path: "", except: :index do
      resources :comments, module: :albums, only: [:index, :create, :destroy]
    end
  end
end

app/views/shared/_comments.html.erb
<div id="comments" data-behavior="show-more-comments" data-comments-url="<%= comments_path %>" data-current-page="<%= comments.current_page %>" data-total-pages="<%= comments.total_pages %>">
  <div class="page-header">
    <%= header_text_with_counter(:h3, "Comment", commentable.comments_count) %>
  </div>

  <% if signed_in? %>
    <%= form_with model: [*commentable_path, Comment.new], data: {behavior: "comment-form"}, local: false do |f| %>
      <div class="form-group">
        <%= f.text_area :body, rows: 3, class: "form-control", placeholder: "Write a comment...", data: {behavior: "write-comment"} %>
      </div>

      <div class="form-group">
        <div class="pull-right">
          <span class="comment-length" data-behavior="comment-length"><%= fa_icon "plus-square-o", text: "280" %></span>
          <%= f.button "Post it", disabled: true, class: "btn btn-success btn-sm", data: {behavior: "post-comment"} %>
        </div>
        <div class="clearfix"></div>
      </div>
    <% end %>
  <% end %>

  <div data-behavior="comments">
    <% if commentable.comments.count == 0 %>
      <h4 data-behavior="no-comments-posted">No comments have been posted for this <%= commentable.class.to_s.downcase %></h4>
    <% else %>
      <%= render partial: "comments/comment", collection: comments, locals: {with_posted_in: false} %>
    <% end %>
  </div>
  <div id="comments-spinner" class="text-center" data-behavior="comments-spinner" hidden>
    <%= fa_icon "spinner pulse spin" %>
  </div>
</div>

app/views/shared/_search.html.erb
<div class="search-form row <%= search_form_visibility(params) %>" data-behavior=<%= "#{type}-search" %>>
  <div class="col-6 offset-3">
    <%= form_with url: path, method: :get, skip_enforcing_utf8: true, class: "form-group justify-content-center", local: true do %>
      <div class="input-group">
        <%= search_field_tag :search, params[:search], class: "form-control form-control-sm", placeholder: "Search #{type.titleize}s...", data: {behavior: "#{type}-search-field"} %>
        <span class="input-group-btn">
          <%= button_tag fa_icon("search"), class: "search-submit btn btn-default btn-sm", name: nil %>
        </span>
      </div>
    <% end %>
  </div>
</div>