config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  # Rails information, in development mode, is provided at:
  #   localhost:3000/rails/info/properties
  #   localhost:3000/rails/info/routes

  # Email previews, in development mode, are provided at:
  #   localhost:3000/rails/mailers
  #
  # This is setup in specs/mailers/previews

  # AUTHENTICATION ROUTES (cookie-based via Clearance Gem)
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]
  resources :users, controller: "users", only: [:create] do
    resource :password, controller: "passwords", only: [:create, :edit, :update]
  end

  resources :users, only: [:update, :destroy]
  # Setup custom "edit_user" path specifically without "edit" in the URL which
  # is usually needed to differentiate between show and edit pages, in this
  # case there will be no show user page so "edit" path value is not needed.
  get "/users/:id" => "users#edit", :as => "edit_user"

  # The Clearance authentication gem by default does not provide email
  # confirmation. This thoughtbot article details how to add email confirmation
  # to Clearance:
  #   https://robots.thoughtbot.com/email-confirmation-with-clearance
  #
  # Setup a custom "confirm_email" path to validate that a newly signed-up user
  # actually is the owner of the specified email address. A confirmation link
  # (sent from UsersController#create via UserMailer#email_confirmation) will
  # be the following route which will contain both user's name and unique
  # confirmation token.
  get "/confirm_email/:name/:token" => "email_confirmations#update", :as => "confirm_email"

  get "log_in" => "clearance/sessions#new"
  get "log_in" => "clearance/sessions#new", :as => "sign_in"
  delete "log_out" => "clearance/sessions#destroy"
  get "sign_up" => "clearance/users#new"

  # API AUTHENTICATION ROUTES (JWT-based via custom application code)
  namespace :api, defaults: {format: :json} do
    post "log_in" => "sessions#create"
    post "passwords" => "passwords#create"
    put "users/passwords/:user_id/password" => "passwords#update"
    patch "users/passwords/:user_id/password" => "passwords#update"
    put "users/:id" => "users#update"
    patch "users/:id" => "users#update"
    delete "users/:id" => "users#destroy"
    post "users" => "users#create"
    get "confirm_email/:name/:token" => "email_confirmations#update"
    get "tokens/new" => "tokens#new"
  end

  # MISCELLANEOUS ROUTES
  root "misc_pages#home"
  get "home" => "misc_pages#home"
  get "about" => "misc_pages#about"
  get "details" => "misc_pages#details"

  # SIDEKIQ MANAGEMENT INTERFACE
  constraints(Clearance::Constraints::SignedIn.new { |user| user.admin? }) do
    mount Sidekiq::Web, at: "/sidekiq"
  end

  # ARTIST AND ALBUM ROUTES
  #
  # Nested resources, Artist and Album, both using FriendlyId with blank
  # controller names.
  #
  # Important, read the following, especially the "small problem" section:
  #   http://jasoncodes.com/posts/rails-3-nested-resource-slugs

  resources :genres, only: [:index, :create]

  resources :artists, only: [:index, :new, :create]
  get "/artists/:id/albums" => "artists/albums#index", :as => "albums_artist"

  get "/comments/:user_id" => "users/comments#index", :as => "user_comments"
  get "/comments/:user_id/comments" => "users/comments#comments"

  resources :albums, only: :index

  resources :artists, path: "", except: [:index, :new, :create] do
    resources :comments, module: :artists, only: [:index, :create, :destroy]
  end

  resources :artists, path: "", only: [] do
    resources :albums, path: "", except: :index do
      resources :comments, module: :albums, only: [:index, :create, :destroy]
    end
  end
end

app/models/album.rb
# frozen_string_literal: true

class Album < ApplicationRecord
  # ASSOCIATIONS
  belongs_to :artist, counter_cache: true, optional: true
  belongs_to :genre
  belongs_to :release_date, optional: true
  has_many :tracks, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  # FRIENDLY ID
  extend FriendlyId
  friendly_id :title, use: :slugged

  # COVER UPLOADER
  mount_uploader :cover, CoverUploader

  # VALIDATIONS
  validates :title, presence: true, uniqueness: {scope: :artist_id}

  # Skip year will only be used in the model spec for performance reasons.
  attr_accessor :skip_year
  validates :year, numericality: {greater_than: 1950,
                                  less_than_or_equal_to: Date.current.year},
                   unless: :skip_year

  validates :genre_id, presence: true

  validate :track_list_format

  validate :cover_size

  # SCOPES

  # Eager load assocations to avoid N+1 performance issue.
  scope :with_relations, -> { includes(:genre, :release_date) }

  scope :random, -> do
    where(id: Album.unscoped.pluck(:id).sample(20)).order(Arel.sql("RANDOM()"))
  end

  scope :spotlight, -> { order(Arel.sql("RANDOM()")).first }

  scope :starts_with_letter, ->(letter) do
    where("substr(title, 1, 1) = ?", letter).order(:title)
  end

  # This complicated find-by-SQL scope is ranking results from the first part
  # of the union (album title matches) higher than results from the second part
  # (track title matches) by ordering first on rank and then by title.  Note,
  # the virtual "rank" column added to each of the SELECT clauses means UNION
  # based deduplication will not work, hence a Ruby side "uniq" call is used to
  # deduplicate; for very large result sets this would be a problem, however in
  # this case it will be fine since there will be a limit of 250 records.
  #
  # Note, for performance reasons the secondary track title search is a simple
  # ILIKE query rather than a full-text query, this results in a about a 100ms
  # speed improvement.
  scope :search, ->(query) do
    find_by_sql([<<-SQL.squish, query, "%#{query}%"])
                   SELECT albums.*, 1 as rank
                     FROM albums
                     WHERE title @@ ?
                   UNION ALL
                   SELECT DISTINCT albums.*, 2 as rank
                     FROM albums
                     JOIN tracks ON tracks.album_id = albums.id
                     WHERE tracks.title ILIKE ?
                   ORDER BY rank, title ASC LIMIT 250
    SQL
      .uniq
  end

  scope :with_genre, ->(genre) do
    joins(:genre).where("genres.name = ?", genre)
  end

  scope :with_release_date, ->(release_dates) do
    joins(:release_date).where("release_dates.year IN (?)", release_dates)
  end

  scope :sort_by_year, ->(direction) do
    joins(:release_date).order("release_dates.year "\
                               "#{direction == :desc ? "DESC" : "ASC"}")
  end

  scope :newest_artist_albums, ->(artist_id) do
    where(artist_id: artist_id).joins(:release_date).order("release_dates.year DESC")
  end

  scope :oldest_artist_albums, ->(artist_id) do
    where(artist_id: artist_id).joins(:release_date).order("release_dates.year ASC")
  end

  scope :longest_artist_albums, ->(artist_id) do
    where(artist_id: artist_id)
      .joins(:tracks)
      .group("albums.id")
      .select(<<-SQL.squish)
                albums.id as id,
                albums.title as title,
                albums.updated_at as updated_at,
                albums.artist_id as artist_id,
                albums.genre_id as genre_id,
                albums.release_date_id as release_date_id,
                albums.cover as cover,
                albums.slug as slug,
                albums.tracks_count as tracks_count,
                albums.comments_count as comments_count,
                sum(tracks.duration) as album_duration
      SQL
      .order("album_duration DESC")
  end

  scope :most_recent, -> do
    joins(:release_date).where(
      "release_dates.year IN (?)",
      [Date.current.year, Date.current.year - 1]
    ).order("release_dates.year DESC").order(updated_at: :desc).limit(6)
  end

  # MODEL FILTER METHODS

  YEAR_RANGE_RE = /\d{4}\.\.\d{4}\z/.freeze
  def self.list(params, per_page = 20)
    if params.key?(:search)
      albums = Album.search(params[:search])
      # Album.search uses a find_by_sql query hence eager loading via the
      # includes method does not work, instead, for Rails 4, one needs to do
      # the following Preloader magic. Information about this refer to:
      #   http://cha1tanya.com/2013/10/26/preload-associations-with-find-by-sql.html
      ActiveRecord::Associations::Preloader.new.preload(albums,
        [:artist, :genre, :release_date])
      return Kaminari.paginate_array(albums).page(params[:page]).per(per_page)
    end

    list_scopes(params, per_page)
  end

  # rubocop:disable Style/IfUnlessModifier
  def self.list_scopes(params, per_page)
    scopes = Album.with_relations

    if params.key?(:random) && params[:random]
      return scopes.random.page(1).per(per_page)
    end

    scopes = scopes.starts_with_letter(params[:letter]) if params.key?(:letter)

    if params.key?(:genre) && params[:genre].present?
      scopes = scopes.with_genre(params[:genre])
    end

    if params.key?(:year) && params[:year].present?
      scopes = scopes.with_release_date(list_scopes_extract_years(params))
    end

    sorted_scopes = list_scopes_sort(params, scopes)
    scopes = sorted_scopes if sorted_scopes

    scopes.page(params[:page]).per(per_page)
  end
  # rubocop:enable Style/IfUnlessModifier

  # rubocop:disable Security/Eval
  def self.list_scopes_extract_years(params)
    years = []
    params[:year].split(",").each do |year|
      if YEAR_RANGE_RE.match?(year)
        years += eval(year).to_a
      else
        years << year.to_i
      end
    end
    years
  end
  # rubocop:enable Security/Eval

  # rubocop:disable Style/GuardClause
  def self.list_scopes_sort(params, scopes)
    direction = :asc
    direction = :desc if params.key?(:order) && params[:order] == "reverse"

    if params.key?(:sort) && params[:sort] == "year"
      scopes.sort_by_year(direction)
    elsif params[:sort] == "title" || !params.key?(:sort)
      scopes.order(title: direction)
    end
  end
  # rubocop:enable Style/GuardClause

  def self.artist_albums(artist_id, params = nil)
    if params.nil? || params[:newest]
      Album.with_relations.newest_artist_albums(artist_id)
    elsif params[:oldest]
      Album.with_relations.oldest_artist_albums(artist_id)
    elsif params[:longest]
      Album.with_relations.longest_artist_albums(artist_id)
    elsif params[:name]
      Album.with_relations.where(artist_id: artist_id).order(:title)
    end
  end

  # FORM RELATED VIRTUAL ATTRIBUTES
  def year
    @year ||= release_date.year if release_date
  end

  def year=(year)
    self.release_date_id = ReleaseDate.find_or_create_by(year: year).id
    @year = year
  end

  def track_list
    @track_list ||= tracks.order(:number).map { |track|
      mins, secs = track.duration.divmod(60)
      "#{track.title} (#{mins}:#{secs.to_s.rjust(2, "0")})"
    }.join("\n")
  end

  def track_list=(list_of_tracks)
    @track_list = list_of_tracks

    # Clear out the existing set of tracks, the new track_list will overwrite
    # them once this model is validated and then saved.
    tracks.clear
  end

  # VIEW HELPERS.
  def tracks_summary
    @tracks_summary ||= tracks.order(:number).limit(6).map { |track|
      "#{track.number}. #{track.title}"
    }

    @tracks_summary << "..." if tracks_count > 6

    # Handle the edge case where an album has been defined without any tracks.
    # This will usually occur upon an album form submission with an empty
    # tracks listing.
    @tracks_summary << "No tracks" if @tracks_summary.empty?
    @tracks_summary
  end

  def total_duration
    return @total_duration if @total_duration

    mins, secs = tracks.sum(:duration).divmod(60)
    @total_duration = "#{mins}:#{secs.to_s.rjust(2, "0")}"
  end

  private

  # Validates track_list whilst also converting the track_list into the
  # individual tracks associated with this album for later saving.
  #
  # If track_list is not in this format then this validation will error.
  def track_list_format
    return unless @track_list

    @track_list.split("\r\n").each.with_index(1) do |track, index|
      Track.parse_form_track(track, index, tracks, errors)
    end
  end

  # Validates the cover size is sane, must not be greater than 500kb. Note,
  # this cover size check occurs after it has been processed, hence why this
  # server side check (at 500kb) is different to the client side check (at
  # 2MB in app/javascript/src/AlbumForm.js).
  def cover_size
    errors.add(:cover, "must be less than 500kb") if cover.size > 500.kilobytes
  end
end

app/controllers/albums/comments_controller.rb
# frozen_string_literal: true

class Albums::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
    artist = Artist.friendly.find(params[:artist_id])
    @commentable = artist.albums.friendly.find(params[:album_id])
    @commentable_path = artist_album_path(artist, @commentable)
  end
end

app/controllers/albums_controller.rb
# frozen_string_literal: true

class AlbumsController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  before_action :set_artist, only: [:new, :create, :update]
  before_action :set_album, only: [:show, :edit, :destroy]

  def index
    @albums = Album.list(params)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def show
    @artist = @album.artist
    @tracks = @album.tracks
    @tracks_count = @album.tracks_count
    @comments = @album.comments.list.page
    @comments_path = request.path + "/comments"
    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    @album = @artist.albums.new
    @back_link = artist_path(@artist)
  end

  def create
    @album = @artist.albums.new(album_params)
    if @album.save
      flash[:notice] = "#{@album.title} has been created"
      redirect_to [@artist, @album]
    else
      flash.now[:alert] = "Album could not be created"
      @back_link = artist_path(@artist)
      render "new", status: :unprocessable_entity
    end
  end

  def edit
    @artist = @album.artist
    @back_link = request.referer || artist_path(@artist)
  end

  def update
    @album = @artist.albums.friendly.find(params[:id])
    @album.slug = nil
    if @album.update(album_params)
      flash[:notice] = "#{@album.title} has been updated"
      redirect_to [@artist, @album]
    else
      flash.now[:alert] = "Album could not be updated"
      @back_link = artist_path(@artist)
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    artist = @album.artist
    @album.destroy!
    @albums_count = artist.albums_count
    respond_to do |format|
      format.html do
        flash[:notice] = "#{@album.title} has been removed"
        redirect_to artist_path(artist)
      end
      format.js
    end
  end

  private

  def set_artist
    @artist = Artist.friendly.find(params[:artist_id])
  end

  def set_album
    @album = Album.friendly.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    if request.format.html?
      flash[:alert] = "The album '#{params[:id]}' does not exist"
      redirect_to albums_path
    else # JSON end-point
      head :not_found
    end
  end

  def album_params
    params.require(:album).permit(
      :title, :genre_id, :year, :track_list, :cover, :cover_cache
    )
  end
end

app/controllers/artists/albums_controller.rb
# frozen_string_literal: true

class Artists::AlbumsController < ApplicationController
  before_action :set_artist, only: [:index]

  def index
    @albums = Album.artist_albums(@artist.id, params)
    @order_name = if params[:newest]
      "newest"
    elsif params[:oldest]
      "oldest"
    elsif params[:longest]
      "longest"
    elsif params[:name]
      "name"
    end
    respond_to do |format|
      format.js
      format.json
    end
  end

  private

  def set_artist
    @artist = Artist.friendly.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The artist '#{params[:id]}' does not exist"
    redirect_to artists_path
  end
end

app/helpers/albums_helper.rb
# frozen_string_literal: true

module AlbumsHelper
  def genre_select(album)
    album.genre.present? ? album.genre.id : Genre.find_by(name: "Rock").id
  end
end

app/views/albums/_album.html.erb
<% cache album do %>
  <div class="col-lg-6">
    <div class="album">
      <h2><%= link_to album.title, [album.artist, album] %> </h2>
      <h3>by <%= link_to album.artist.name, album.artist %> <small><%= "(#{album.tracks_count} Tracks)" %></small></h3>
      <div class="icon">
        <%= link_to albums_path(year: album.release_date.year) do %>
          <%= fa_icon "calendar", text: "#{album.release_date.year}" %>
        <% end %>
        <%= link_to albums_path(genre: album.genre.name), class: "spacer-left-xs" do %>
          <%= fa_icon "tag", text: "#{album.genre.name}" %>
        <% end %>
        <%= link_to artist_album_path(album.artist, album, anchor: "comments"), class: "artist-album-comments" do %>
          <%= fa_icon "comment-o", text: "#{album.comments_count}", class: "spacer-left-xs" %>
        <% end %>
      </div>
      <div>
        <%= link_to [album.artist, album] do %>
          <%= image_tag(album.cover.small.url, class: "img-responsive") if album.cover? %>
        <% end %>
        <ul>
          <% album.tracks_summary.each do |track_title| %>
            <li><%= track_title %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/albums/_filter.html.erb
<div class="filter col-md-12" data-behavior="album-filter" <%= filter_visibility %>>
  <%= form_with url: albums_path, method: :get, skip_enforcing_utf8: true, button: nil, data: {behavior: "album-filter-form"}, local: true do %>
    <div class="form-group col-md-2 col-md-offset-2">
      <%= label_tag :genre, nil, class: "control-label" %>
      <%= select_tag :genre, options_from_collection_for_select(Genre.order(:name), :name, :name), {include_blank: "Choose", class: "form-control input-sm"} %>
    </div>
    <div class="form-group col-md-2">
      <%= label_tag "Year(s)", nil, class: "control-label" %>
      <%= text_field_tag :year, nil, class: "form-control input-sm", placeholder: "2000, 2004..2008", pattern: "[0-9., ]+" %>
    </div>
    <div class="form-group col-md-1">
      <%= label_tag :sort , nil, class: "control-label" %>
      <div class="radio radio-first">
        <label><%= radio_button_tag :sort, :title, true %>Title</label>
      </div>
      <div class="radio radio-last">
        <label><%= radio_button_tag :sort, :year %>Year</label>
      </div>
    </div>
    <div class="form-group col-md-1">
      <%= label_tag :order, nil, class: "control-label" %>
      <div class="radio radio-first">
        <label><%= radio_button_tag :order, :forward, true %>Forward</label>
      </div>
      <div class="radio radio-last">
        <label><%= radio_button_tag :order, :reverse %>Reverse</label>
      </div>
    </div>
    <div class="form-group col-md-1">
      <%= button_tag "Select", class: "submit btn btn-success btn-sm", name: nil, data: {disable_with: "#{fa_icon('spinner spin')} Selecting..."} %>
    </div>
  <% end %>
</div>

app/views/albums/_form.html.erb
<div class="well">
  <%= form_with model: [artist, album], class: "form-horizontal", multipart: true, id: "album-form", local: true, data: { turbo: false } do |f| %>
    <ul class="list-group" data-behavior="album-form-errors">
      <% if album.errors.any? %>
        <% album.errors.full_messages.each do |msg| %>
          <li class="list-group-item list-group-item-danger"><%= msg %></li>
        <% end %>
      <% end %>
    </ul>

    <div class="form-group <%= error?(album, :title) %>" data-behavior="album-title">
      <%= f.label :title, class: "col-md-2 control-label" %>
      <div class="col-md-9">
        <%= f.text_field :title, class: "form-control", placeholder: "The Album" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :genre_id, class: "col-md-2 control-label" %>
      <div class="col-md-9">
        <%= f.collection_select :genre_id, Genre.order(:name), :id, :name, {selected: genre_select(album)}, {class: "form-control", data: {behavior: "new-genre"}} %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-2 col-md-9">
        <%= link_to fa_icon("plus", text: "Genre"), "#", class: "btn btn-default btn-xs", data: {toggle: "modal", target: "#new-genre"} %>
      </div>
    </div>

    <div class="form-group <%= error?(album, :year) %>">
      <%= f.label :year, class: "col-md-2 control-label" %>
      <div class="col-md-9">
        <%= f.number_field :year, class: "form-control", placeholder: Time.current.year %>
      </div>
    </div>

    <div class="form-group <%= error?(album, :track_list) %>">
      <%= f.label :track_list, class: "col-md-2 control-label" %>
      <div class="col-md-9">
        <%= f.text_area :track_list, rows: 12, class: "form-control", placeholder: "First Track (5:26)\nSecond Track (4:45)" %>
      </div>
    </div>

    <div class="form-group" data-behavior="album-cover">
      <%= f.label :cover, class: "col-md-2 control-label" %>
      <div class="col-md-9">
        <%= f.file_field :cover, accept: "image/jpeg" %>
        <%= f.hidden_field :cover_cache %>
        <%= image_tag(album.cover.small.url, class: "img-responsive", data: {behavior: "cover-image"}) if album.cover? %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-2 col-md-9">
        <%= link_to "Cancel", back_link, class: "btn btn-default btn-sm" %>
        <%= f.button "Submit", class: "btn btn-success btn-sm", data: {disable_with: "#{fa_icon('spinner spin')} Submitting..."} %>
      </div>
    </div>
  <% end %>
</div>

<div class="modal fade" id="new-genre" tabindex="-1">
  <%= form_with model: Genre.new, url: genres_path, local: false do |f| %>
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h2 class="modal-title">New Genre</h2>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <%= f.text_field :name, class: "form-control", placeholder: "Genre" %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
          <%= f.button "Add", class: "btn btn-success btn-sm",data: {disable_with: "#{fa_icon('spinner spin')} Adding..."} %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/albums/destroy.js.erb
<% unless Rails.env.test? %>
  Turbo.clearCache();
<% end %>
$("[data-behavior~=flash-messages]").empty();
$("[data-behavior~=artist-album-<%= @album.id %>]").fadeOut(500, function() {
  $("[data-behavior~=artist-album-<%= @album.id %>]").remove();
});

function albumCountsHeader() {
  var albumsCount = parseInt(<%= @albums_count %>);

  if (albumsCount === 0) {
    return "(0 Albums)";
  } else if (albumsCount === 1) {
    return "(1 Album)";
  } else {
    return "(" + albumsCount + " Albums)";
  }
}

var header = albumCountsHeader();
$("[data-behavior~=album-header-counter]").text(header);

app/views/albums/edit.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="page-header">
      <h1>Edit Album <small><%= "for #{@artist.name}" %></small></h1>
    </div>

    <%= render "form", album: @album, artist: @artist, back_link: @back_link %>
  </div>
</div>

app/views/albums/index.html.erb
<% title("Platters - Albums") %>
<div id="albums">
  <div class="page-header">
    <%= header_text_with_counter(:h1, "Album", @albums.total_count) %>
  </div>

  <div class="list-choice text-center">
    <ul class="pagination pagination-sm">
      <li><%= link_to "All", albums_path %></li>
      <% unless params.key?(:search) || params.key?(:random) %>
        <% ("A".."Z").each do |letter| %>
          <li data-behavior="album-letter-picker" class="<%= letter_activity(params, letter) %>"><%= link_to letter, albums_path(add_letter(letter)) %></li>
        <% end %>
      <% end %>
      <li>
        <%= link_to albums_path(random: true), class: "random-link", title: "Random", data: {toggle: "tooltip"} do %>
          <%= fa_icon "random" %>
        <% end %>
      </li>
      <li><a class="filter-link" title="Filter" data-toggle="tooltip" data-behavior="album-filter-link"><%= fa_icon "filter" %></a></li>
      <li><a class="search-link" title="Search" data-toggle="tooltip" data-behavior="album-search-link"><%= fa_icon "search" %></a></li>
    </ul>
  </div>

  <%= render partial: "filter" %>
  <%= render partial: "shared/search", locals: {type: "album", path: albums_path} %>

  <% if @albums.empty? %>
    <h4 class="text-center">No matching albums</h4>
  <% else %>
    <%= render partial: "album", collection: @albums %>
    <div class="col-md-8">
      <%= paginate @albums %>
    </div>
  <% end %>
</div>

app/views/albums/new.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="page-header">
      <h1>Add Album <small><%= "for #{@artist.name}" %></small></h1>
    </div>

    <%= render "form", album: @album, artist: @artist, back_link: @back_link %>
  </div>
</div>

app/views/albums/show.html.erb
<% title(@album.title) %>
<div id="album">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="page-header">
        <div class="pull-left">
          <h1><%= @album.title %> <small>by <%= link_to @artist.name, @artist %></small></h1>
        </div>
        <% if signed_in_as_admin? %>
          <div class="pull-right">
            <ul class="list-inline">
              <li>
                <%= link_to artist_album_path(@artist, @album), class: "spacer-left-xs action", method: :delete, data: {confirm: "Are you sure you want to remove #{@album.title}?"} do %>
                  <%= fa_icon "remove" %> Remove
                <% end %>
              </li>
              <li>
                <%= link_to edit_artist_album_path(@artist, @album), class: "action" do %>
                  <%= fa_icon "edit" %> Edit
                <% end %>
              </li>
            </ul>
          </div>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>

    <div class="col-md-4 col-md-offset-1">
      <%= image_tag(@album.cover.url, class: "img-responsive center-block") if @album.cover? %>
    </div>

    <div class="col-md-6">
      <h2><%= @tracks_count %> Tracks <small><%= "(Time #{@album.total_duration})" %></small></h2>
      <span class="icon">
        <%= link_to albums_path(year: @album.release_date.year) do %>
          <%= fa_icon "calendar", text: "#{@album.release_date.year}" %>
        <% end %>
        <%= link_to albums_path(genre: @album.genre.name), class: "spacer-left-xs" do %>
          <%= fa_icon "tag", text: "#{@album.genre.name}" %>
        <% end %>
      </span>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>No.</th>
            <th>Title</th>
            <th>Duration</th>
          </tr>
        </thead>
        <tbody>
          <% @tracks.order(:number).each do |track| %>
            <% if track.number <= 20 %>
              <tr class="visible">
            <% else %>
              <tr class="invisible" data-behavior="track-toggle-visibility">
            <% end %>
                <td><%= track.number.to_s << "." %></td>
                <td><%= track.title %></td>
                <td><%= track.duration_display %></td>
              </tr>
          <% end %>
        </tbody>
      </table>
      <% if @tracks_count > 20 %>
        <div class="tracks-gradient">
        </div>
        <div id="tracks-visibility-anchor" class="tracks-visibility-controls">
          <%= button_tag fa_icon("angle-double-down fw", text: "Show all tracks"),  class: "btn btn-default btn-sm",           data: {behavior: "album-show-all-tracks"} %>
          <%= button_tag fa_icon("angle-double-up fw",   text: "Show less tracks"), class: "invisible btn btn-default btn-sm", data: {behavior: "album-show-less-tracks"} %>
        </div>
      <% end %>
    </div>

    <div class="col-md-10 col-md-offset-1">
      <%= render partial: "shared/comments", locals: {comments: @comments, comments_path: @comments_path, commentable: @album, commentable_path: [@artist, @album]} %>
    </div>
  </div>
</div>