config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  # Rails information, in development mode, is provided at:
  #   localhost:3000/rails/info/properties
  #   localhost:3000/rails/info/routes

  # Email previews, in development mode, are provided at:
  #   localhost:3000/rails/mailers
  #
  # This is setup in specs/mailers/previews

  # AUTHENTICATION ROUTES (cookie-based via Clearance Gem)
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]
  resources :users, controller: "users", only: [:create] do
    resource :password, controller: "passwords", only: [:create, :edit, :update]
  end

  resources :users, only: [:update, :destroy]
  # Setup custom "edit_user" path specifically without "edit" in the URL which
  # is usually needed to differentiate between show and edit pages, in this
  # case there will be no show user page so "edit" path value is not needed.
  get "/users/:id" => "users#edit", :as => "edit_user"

  # The Clearance authentication gem by default does not provide email
  # confirmation. This thoughtbot article details how to add email confirmation
  # to Clearance:
  #   https://robots.thoughtbot.com/email-confirmation-with-clearance
  #
  # Setup a custom "confirm_email" path to validate that a newly signed-up user
  # actually is the owner of the specified email address. A confirmation link
  # (sent from UsersController#create via UserMailer#email_confirmation) will
  # be the following route which will contain both user's name and unique
  # confirmation token.
  get "/confirm_email/:name/:token" => "email_confirmations#update", :as => "confirm_email"

  get "log_in" => "clearance/sessions#new"
  get "log_in" => "clearance/sessions#new", :as => "sign_in"
  delete "log_out" => "clearance/sessions#destroy"
  get "sign_up" => "clearance/users#new"

  # API AUTHENTICATION ROUTES (JWT-based via custom application code)
  namespace :api, defaults: {format: :json} do
    post "log_in" => "sessions#create"
    post "passwords" => "passwords#create"
    put "users/passwords/:user_id/password" => "passwords#update"
    patch "users/passwords/:user_id/password" => "passwords#update"
    put "users/:id" => "users#update"
    patch "users/:id" => "users#update"
    delete "users/:id" => "users#destroy"
    post "users" => "users#create"
    get "confirm_email/:name/:token" => "email_confirmations#update"
    get "tokens/new" => "tokens#new"
  end

  # MISCELLANEOUS ROUTES
  root "misc_pages#home"
  get "home" => "misc_pages#home"
  get "about" => "misc_pages#about"
  get "details" => "misc_pages#details"

  # SIDEKIQ MANAGEMENT INTERFACE
  constraints(Clearance::Constraints::SignedIn.new { |user| user.admin? }) do
    mount Sidekiq::Web, at: "/sidekiq"
  end

  # ARTIST AND ALBUM ROUTES
  #
  # Nested resources, Artist and Album, both using FriendlyId with blank
  # controller names.
  #
  # Important, read the following, especially the "small problem" section:
  #   http://jasoncodes.com/posts/rails-3-nested-resource-slugs

  resources :genres, only: [:index, :create]

  resources :artists, only: [:index, :new, :create]
  get "/artists/:id/albums" => "artists/albums#index", :as => "albums_artist"

  get "/comments/:user_id" => "users/comments#index", :as => "user_comments"
  get "/comments/:user_id/comments" => "users/comments#comments"

  resources :albums, only: :index

  resources :artists, path: "", except: [:index, :new, :create] do
    resources :comments, module: :artists, only: [:index, :create, :destroy]
  end

  resources :artists, path: "", only: [] do
    resources :albums, path: "", except: :index do
      resources :comments, module: :albums, only: [:index, :create, :destroy]
    end
  end
end

app/views/layouts/_footer.html.erb
<footer id="platters-footer">
  <div class="container-fluid">
    <div class="float-right">
      <small>
        <ul>
          <li><%= link_to "About",   about_path,   class: "spacer-right-sm" %></li>
          <li><%= link_to "Details", details_path, class: "spacer-right-sm" %></li>
        </ul>
      </small>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header id="platters-header">
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: "navbar-brand" do %>
          <%= image_tag "platters-white.svg" %> platters
        <% end %>
      </div>
      <div class="collapse navbar-collapse" id="collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Artists", artists_path %></li>
          <li><%= link_to "Albums", albums_path %></li>
        </ul>
        <% if signed_out? %>
          <div class="navbar-right">
            <ul class="nav navbar-nav">
              <li><%= link_to "Log in", log_in_path %></li>
              <li><%= link_to "Sign up", sign_up_path %></li>
            </ul>
          </div>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= fa_icon "user fw", text: current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to fa_icon("comment-o fw", text: "&nbsp;Comments".html_safe), user_comments_path(current_user) %></li>
                <li><%= link_to fa_icon("gear fw", text: "&nbsp;Account".html_safe), edit_user_path(current_user) %></li>
                <li><%= link_to fa_icon("sign-out fw", text: "&nbsp;Log out".html_safe), log_out_path, method: :delete %></li>
              </ul>
            </li>
          </ul>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>
    <% if content_for?(:title) %>
      <%= yield(:title) %>
    <% else %>
      Platters
    <% end %>
  </title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  <meta name="turbo-cache-control" content="<%= turbo_cache_control %>">
</head>
<body>
  <%= render "layouts/header" %>
  <div class="main">
    <div class="flash-messages" data-behavior="flash-messages">
      <% flash.each do |key, message| %>
        <div class="flash-message alert alert-dismissible alert-<%= key %> fade in">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <% if key == "alert" %>
            <%= fa_icon "warning fw" %>
          <% elsif key == "notice" || key == "success" %>
            <%= fa_icon "info-circle fw" %>
          <% end %>
          <%= message %>
        </div>
      <% end %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </div>
  <%= render "layouts/footer" %>
</body>
</html>